name: Docker Image CI
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u israelzaleta55 -p hwd^KT(xU6J.y3L
      - name: Build Docker Image
        run: docker build . --file dockerfile.dev -t israelzaleta55/starter:$(date +%s)
      - name: Push Docker Image to DockerHub
        run: docker push israelzaleta55/starter

# israelzaleta55
# hwd^KT(xU6J.y3L
  